#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Thu Aug 13 01:34:07 UTC 2026
alwaysLogTamperWarnings=false
